---
homebrew_repo: https://github.com/Homebrew/brew
homebrew_version: "5.0.7" # renovate: datasource=github-releases depName=Homebrew/brew versioning=semver

homebrew_mac_taps:
  - cncf/landscape2
  - siderolabs/tap
homebrew_mac_packages:
  - yadm
  - kubectl
  - helm
  - go
  - ansible
  - ansible-lint
  - azure-cli
  - cilium-cli
  - cocogitto
  - git
  - goreleaser
  - hcloud
  - helm-docs
  - jq
  - k9s
  - krew
  - kubectx
  - kubelogin
  - pipx
  - nvm
  - podman
  - restic
  - socket_vmnet
  - tfenv
  - terraform-docs
  - tflint
  - yq
  - golangci-lint
  - pre-commit
  - tofuenv
  - operator-sdk
  - mas
  - awscli
  - fio
  - cncf/landscape2/landscape2
  - siderolabs/tap/talosctl
  - session-manager-plugin
homebrew_mac_casks:
  - visual-studio-code
  - ghostty
  - dotnet-sdk
  - firefox
  - ente-auth
  - git-credential-manager
  - rectangle
  - soundsource
  - stats
  - termius
  - slack
  - tunnelblick
  - proton-mail
  - proton-pass
  - spotify
  - webex
  - microsoft-outlook
  - scroll-reverser
  - microsoft-teams
  - elgato-stream-deck
  - cyberduck

homebrew_linux_taps:
  - cncf/landscape2
  - siderolabs/tap
homebrew_linux_packages:
  - yadm
  - kubectl
  - helm
  - cilium-cli
  - cocogitto
  - golangci-lint
  - goreleaser
  - hcloud
  - helm-docs
  - k9s
  - krew
  - kubectx
  - kubelogin
  - restic
  - tfenv
  - terraform-docs
  - tflint
  - yq
  - nvm
  - tofuenv
  - operator-sdk
  - awscli
  - cncf/landscape2/landscape2
  - siderolabs/tap/talosctl
homebrew_linux_casks: []
