# code: language=ansible
---
- name: Set download url
  ansible.builtin.set_fact:
    ente_auth_appimage_download_url: "https://github.com/ente-io/ente/releases/download/auth-{{ ente_auth_appimage_version }}/ente-auth-{{ ente_auth_appimage_version }}-x86_64.AppImage"

- name: Download ente-auth AppImage
  ansible.builtin.get_url:
    url: "{{ ente_auth_appimage_download_url }}"
    dest: /tmp/ente-auth.AppImage
    mode: "0755"
    force: true

- name: Install ente-auth
  become: true
  changed_when: install_ente_auth.rc == 0
  ansible.builtin.command:
    cmd: install /tmp/ente-auth.AppImage /usr/local/bin/ente-auth
  register: install_ente_auth

- name: Template .desktop file
  ansible.builtin.template:
    src: templates/ente-auth.desktop.j2
    dest: "/tmp/ente-auth.desktop"
    mode: "0644"

- name: Ensure icons directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.icons"
    state: directory
    mode: "0755"

- name: Copy ente-auth icon
  ansible.builtin.copy:
    src: files/ente-auth-icon.png
    dest: "{{ ansible_facts['user_dir'] }}/.icons/ente-auth-icon.png"
    force: true
    mode: "0644"

- name: Install desktop file
  changed_when: install_desktop_file.rc == 0
  ansible.builtin.command:
    cmd: "desktop-file-install --dir={{ ansible_facts['user_dir'] }}/.local/share/applications /tmp/ente-auth.desktop"
  register: install_desktop_file

- name: Remove downloaded AppImage
  ansible.builtin.file:
    path: /tmp/ente-auth.AppImage
    state: absent

- name: Remove downloaded AppImage
  ansible.builtin.file:
    path: /tmp/ente-auth.AppImage
    state: absent
